# BUCKET - Consultant
apiVersion: bucket/v1
kind: Schema
metadata:
  name: spica-real-estate-consultant-bucket
spec:
  title: Consultant
  description: Consultant Bucket
  icon: home_work
  primary: mail
  readOnly: false
  history: false
  properties:
    name:
      type: string
      title: name
      description: Description of the Name input
      options:
        position: bottom
    surname:
      type: string
      title: surname
      description: Description of the surname input
      options:
        position: bottom
    mail:
      type: string
      title: mail
      description: Description of the mail input
      options:
        position: bottom
    phone_number:
      type: string
      title: phone_number
      description: Description of the phone_number input
      options:
        position: bottom
    thumbnail:
      type: storage
      title: thumbnail
      description: Description of the thumbnail input
      options:
        position: bottom
  acl:
    write: true==true
    read: true==true
  order: 27
---
# BUCKET - Adverst
apiVersion: bucket/v1
kind: Schema
metadata:
  name: spica-real-estate-adverst-bucket
spec:
  title: Adverst
  description: Adverst Bucket
  icon: home_work
  primary: name
  readOnly: false
  history: false
  properties:
    adverst_no:
      type: number
      title: adverst_no
      description: adverst_no of adverst
      options:
        position: left
    name:
      type: string
      title: name
      description: Description of the name input
      options:
        position: left
    description:
      type: textarea
      title: description
      description: description of adverst
      options:
        position: right
    square_meters:
      type: string
      title: square_meters
      description: Description of the square_meters input
      options:
        position: left
    room_count:
      type: string
      title: room_count
      description: room_count of  adverst
      options:
        position: left
    warming_type:
      type: string
      title: warming_type
      description: warming_type of adverst
      options:
        position: right
      enum:
        - furnace
        - boiler
        - gas-fired
        - electric
    adverst_status:
      type: string
      title: adverst_status
      description: adverst_status of adverst
      options:
        position: right
      enum:
        - rent
        - sale
    livingroom_count:
      type: string
      title: livingroom_count
      description: livingroom_count of adverst
      options:
        position: right
    fuel_type:
      type: string
      title: fuel_type
      description: fuel_type of adverst
      options:
        position: left
      enum:
        - coal
        - gas
        - wood
        - electric
    staff_no:
      type: string
      title: staff_no
      description: staff_no of adverst
      options:
        position: left
    building_age:
      type: string
      title: building_age
      description: building_age of adverst
      options:
        position: left
    bathroom_count:
      type: string
      title: bathroom_count
      description: bathroom_count of adverst
      options:
        position: left
    trade:
      type: boolean
      title: trade
      description: trade of adverst
      options:
        position: right
      default: false
    bedroom_count:
      type: string
      title: bedroom_count
      description: bedroom_count of adverst
      options:
        position: right
    address:
      type: object
      title: address
      description: Description of the address input
      options:
        position: left
      properties:
        country:
          type: string
          title: country
          description: Description of the country input
          options:
            position: bottom
        district:
          type: string
          title: district
          description: Description of the district input
          options:
            position: bottom
        city:
          type: string
          title: city
          description: Description of the city input
          options:
            position: bottom
    location:
      type: location
      title: location
      description: Description of the location input
      options:
        position: bottom
      locationType: Point
    created_at:
      type: date
      title: created_at
      description: created_at of adverst
      options:
        position: right
      default: :created_at
    consultant:
      type: relation
      title: consultant
      description: Description of the consultant input
      options:
        position: bottom
      relationType: onetoone
      dependent: false
      primary: mail
      bucket:
        resourceFieldRef:
          schemaName: spica-real-estate-consultant-bucket
    properties:
      type: object
      title: properties
      description: Description of the properties input
      options:
        position: bottom
      properties:
        exterior:
          type: multiselect
          title: exterior
          description: Description of the exterior input
          options:
            position: bottom
          items:
            type: string
        interior:
          type: multiselect
          title: interior
          description: Description of the interior input
          options:
            position: bottom
          items:
            type: string
        environmental:
          type: multiselect
          title: environmental
          description: Description of the environmental input
          options:
            position: bottom
          items:
            type: string
    categories:
      type: relation
      title: categories
      description: Description of the categories input
      options:
        position: bottom
      relationType: onetomany
      dependent: false
      primary: name
      bucket:
        resourceFieldRef:
          schemaName: spica-real-estate-category-bucket
    cover_img:
      type: storage
      title: cover_img
      description: Description of the cover_img input
      options:
        position: bottom
    images:
      type: array
      title: images
      description: Description of the images input
      options:
        position: bottom
      items:
        title: Title of the items
        type: storage
    price:
      type: number
      title: price
      description: Description of the price input
      options:
        position: left
    currency:
      type: string
      title: currency
      description: Description of the currency input
      options:
        position: left
      pattern: ""
      enum:
        - EUR
        - GBP
        - USD
  acl:
    write: true==true
    read: true==true
  order: 28
---
# BUCKET - Usefull Link
apiVersion: bucket/v1
kind: Schema
metadata:
  name: spica-real-estate-usefull-link-bucket
spec:
  title: Usefull Link
  description: Link Bucket
  icon: home_work
  primary: name
  readOnly: false
  history: false
  properties:
    link:
      type: string
      title: link
      description: Description of the link input
      options:
        position: bottom
    name:
      type: string
      title: name
      description: name of link
      options:
        position: bottom
  acl:
    write: true==true
    read: true==true
  order: 29
---
# BUCKET - Announcement
apiVersion: bucket/v1
kind: Schema
metadata:
  name: spica-real-estate-announcement-bucket
spec:
  title: Announcement
  description: Announcement Bucket
  icon: home_work
  primary: name
  readOnly: false
  history: false
  properties:
    description:
      type: textarea
      title: description
      description: Description of the row
      options:
        position: right
    name:
      type: string
      title: name
      description: name of announcement
      options:
        position: bottom
    created_at:
      type: date
      title: created_at
      description: created_at of announcement
      options:
        position: right
      default: :created_at
  acl:
    write: true==true
    read: true==true
  order: 30
---
# BUCKET - Category
apiVersion: bucket/v1
kind: Schema
metadata:
  name: spica-real-estate-category-bucket
spec:
  title: Category
  description: Category Bucket
  icon: home_work
  primary: name
  readOnly: false
  history: false
  properties:
    name:
      type: string
      title: name
      description: name of category
      options:
        position: bottom
    sub_categories:
      type: relation
      title: sub_categories
      description: Description of the sub_categories input
      options:
        position: bottom
      relationType: onetomany
      dependent: false
      bucket:
        resourceFieldRef:
          schemaName: spica-real-estate-category-bucket
  acl:
    write: true==true
    read: true==true
  order: 31
---
# BUCKET - About Us
apiVersion: bucket/v1
kind: Schema
metadata:
  name: spica-real-estate-about-us-bucket
spec:
  title: About Us
  description: About Us Bucket
  icon: home_work
  primary: about
  readOnly: false
  history: false
  properties:
    about:
      type: textarea
      title: about
      description: about of category
      options:
        position: bottom
    offices:
      type: array
      title: offices
      description: Description of the offices input
      options:
        position: bottom
      items:
        title: Title of the items
        type: object
        properties:
          address:
            type: string
            title: address
            description: Description of the address input
            options:
              position: bottom
          email:
            type: string
            title: email
            description: Description of the email input
            options:
              position: bottom
          phone:
            type: string
            title: phone
            description: Description of the phone input
            options:
              position: bottom
          title:
            type: string
            title: title
            description: Description of the title input
            options:
              position: bottom
          location:
            type: location
            title: location
            description: Description of the location input
            options:
              position: bottom
            locationType: Point
  acl:
    write: true==true
    read: true==true
  order: 32